name       : unclutter-xfixes
version    : '1.5'
release    : 2
source     :
    - https://github.com/Airblader/unclutter-xfixes/archive/v1.5.tar.gz : 35c75ad24be989dd6708db1d9ce9b2a2f814b80638c0633cdb075c6df090ed11
license    : MIT
component  : system.utils
summary    : Unclutter hides your X mouse cursor when you do not need it, to prevent it from getting in the way.
description: |
    Unclutter hides your X mouse cursor when you do not need it, to prevent it from getting in the way.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - asciidoc
    - libev-devel
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/licenses
