name       : unclutter-xfixes
version    : 1.1
release    : 1
source     :
    - https://github.com/Airblader/unclutter-xfixes/archive/v1.1.tar.gz : 91635c64a2075cb4e8926d84c09931c957e5f1d824a249cddb7ec109378090ad
license    : MIT
component  : xorg.apps
summary    : Unclutter hides your X mouse cursor when you do not need it, to prevent it from getting in the way.
description: |
    Unclutter hides your X mouse cursor when you do not need it, to prevent it from getting in the way.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - asciidoc
    - libev-devel
build      : |
    %make
install    : |
    %make_install